import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'installation',
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/index',
          label: 'Exports',
        },
        ...require('./docs/api/typedoc-sidebar.cjs'),
      ],
    },
  ],
  examples: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    }
  ],
};

export default sidebars;
