name: Build and publish website

on:
  push:
    branches:
      - "master"

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        
      - run: yarn build
      - run: yarn --cwd website install --frozen-lockfile
      - run: yarn --cwd website build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
